language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACChYzJJSq/6UKETDl9Fje95omOa/qAbHc6lbBB9m2pPKwAAAJiP7DuHj+w7
hwAAAAtzc2gtZWQyNTUxOQAAACChYzJJSq/6UKETDl9Fje95omOa/qAbHc6lbBB9m2pPKw
AAAEALS3GGK2rDJrMCdcj5oetdz5k0xgACxwRi9OXXOJEhmaFjMklKr/pQoRMOX0WN73mi
Y5r+oBsdzqVsEH2bak8rAAAAEDI4MDg0MTgwNEBxcS5jb20BAgMEBQ==
  keep_history: true
  on:
    branch: master